# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thuduchospital-peer
  labels:
    app: thuduchospital-peer
spec:
  serviceName: thuduchospital-peer
  replicas: 1
  selector:
    matchLabels:
      app: thuduchospital-peer
  template:
    metadata:
      labels:
        app: thuduchospital-peer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-master
                operator: In
                values:
                - "1"
      containers:
      - name: thuduchospital-peer
        # Image used
        image: nhutori4/thuduchospital-peer:dev
        # Uncomment the following during development/testing of the image
        imagePullPolicy: Always
        env:
          - name: FABRIC_LOGGING_SPEC
            value: INFO
          - name: ORDERER_ADDRESS
            value: healthcare-orderer-clusterip:30750
          - name: ORG_CONTEXT
            value: thuduchospital
          - name: CORE_PEER_ADDRESS
          # value: thuduchospital-peer-clusterip:30751
            value: thuduchospital-peer-clusterip:30751
          - name: CORE_PEER_LOCALMSPID
            value: msp
          - name: FABRIC_LOGGING_SPEC
            value: debug
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: thuduchospital-peer-clusterip:30751
          - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
            value: "true"
          # Replacement for set-context in alpine
          # - name: MSP_ID
          #   value: AcmeMSP
          # - name: ORG_NAME
          #   value: AcmeMSP
          # - name: CORE_PEER_MSPCONFIGPATH
          #   value:  /var/hyperledger/config/users/Admin@acme.com/msp
        volumeMounts:
        - name: thuduchospital-peer-ledger
          mountPath: /var/ledger
        - name: thuduchospital
          mountPath: /mnt/disks/org/ThuDucOrg/peer1/fabric-ca-client/
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: thuduchospital
        hostPath:
          path: /mnt/disks/org/ThuDucOrg/peer1/fabric-ca-client/
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata: 
      name: thuduchospital-peer-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: storageclass-thuduchospital
      resources:
        requests:
          storage: 1Gi

---
# Expose the port 7051 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: thuduchospital-peer-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: thuduchospital-peer

  ports:
    - name: thuduchospital-peer-clusterip
      port: 30751
    - name: thuduchospital-peer-cc-clusterip
      port: 30752

  type: ClusterIP

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: thuduchospital-peer-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: thuduchospital-peer

  ports:
    - name: thuduchospital-peer-nodeport-751
      port: 30751
      nodePort: 30751
    - name: thuduchospital-peer-cc-nodeport-752
      port: 30752
      nodePort: 30752

  type: NodePort